# - name: ensure services are stopped
#   community.general.snap:
#     name: amazon-ssm-agent
#     state: absent
# TODO taking this out as machine at this stage reports
# that aws-ssm-agent is not installed at all

- name: ensure services are stopped and disabled for first boot
  systemd:
    enabled: no
    name: '{{ item }}'
    state: stopped
  with_items:
    #- snapd
    - postgresql
    - pgbouncer
    - fail2ban
    - motd-news
    - vector

- name: Remove snapd
  apt:
    state: absent
    pkg:
      - snapd

# - name: ensure services are stopped and disabled for first boot
#   systemd:
#     enabled: no
#     name: '{{ item }}'
#     state: stopped
#     masked: yes
#   with_items:
#     - lvm2-monitor
# machine at this stage reports this service is stopped and disabled


- name: disable man-db
  become: yes
  file:
    state: absent
    path: "/etc/cron.daily/{{ item }}"
  with_items:
    - man-db
    - popularity-contest
    - ubuntu-advantage-tools
