- hosts: localhost
  become: yes

  vars:
    sql_files:
      - "/tmp/ansible-playbook/files/pgbouncer_config/pgbouncer_auth_schema.sql"
      - "/tmp/ansible-playbook/files/stat_extension.sql"


  tasks:
    - set_fact:
        supabase_internal: true
      tags:
        - install-supabase-internal

    - set_fact:
        parallel_jobs: 16
    
    - name: locale-gen
      command: sudo locale-gen en_US.UTF-8

    # - name: Ensure en_US.UTF-8 locale is enabled
    #   shell: |
    #     echo "LC_ALL=en_US.UTF-8" >> /etc/environment
    #     echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    #     echo "LANG=en_US.UTF-8" > /etc/locale.conf
    #     locale-gen en_US.UTF-8      
    #   become: yes

    - name: check locales
      command: locale -a
      register: locales 

    - name: Install Postgres from nix binary cache
      import_tasks: stage2-setup-postgres.yml

    - name: First boot optimizations
      import_tasks: optimizations.yml

    - name: Run unit tests
      import_tasks: test-image.yml
      tags:
        - unit-tests
