- name: Install Postgres from nix binary cache
  become: yes
  shell: |
    sudo -u postgres bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install github:supabase/postgres#psql_15/bin"

- name: Install glibcLocales from nix binary cache
  become: yes
  shell: |
    sudo -u postgres bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install nixpkgs#glibcLocales"

#TODO include ls $(nix profile list | grep glibc-locales | tail -n 1 | cut -d ':' -f 2 | sed 's/^[ \t]*//')/lib/locale-archive

- name: Ensure /usr/lib/postgresql/bin directory exists
  file:
    path: /usr/lib/postgresql/bin
    state: directory
    owner: postgres
    group: postgres


- name: Ensure /usr/lib/postgresql/share directory exists
  file:
    path: /usr/lib/postgresql/share/postgresql
    state: directory
    owner: postgres
    group: postgres

- name: Ensure /usr/lib/postgresql/share/contrib directory exists
  file:
    path: /usr/lib/postgresql/share/postgresql/contrib
    state: directory
    owner: postgres
    group: postgres

- name: Ensure /usr/lib/postgresql/share/timezonesets directory exists
  file:
    path: /usr/lib/postgresql/share/postgresql/timezonesets
    state: directory
    owner: postgres
    group: postgres

- name: Ensure /usr/lib/postgresql/share/tsearch_data directory exists
  file:
    path: /usr/lib/postgresql/share/postgresql/tsearch_data
    state: directory
    owner: postgres
    group: postgres

- name: Ensure /usr/lib/postgresql/share/extension directory exists
  file:
    path: /usr/lib/postgresql/share/postgresql/extension
    state: directory
    owner: postgres
    group: postgres

- name: import pgsodium_getkey script
  template:
    src: /tmp/ansible-playbook/files/pgsodium_getkey_readonly.sh.j2
    dest: "/usr/lib/postgresql/bin/pgsodium_getkey.sh"
    owner: postgres
    group: postgres
    mode: 0700

- name: Create symbolic links from /home/postgres/.nix-profile/bin to /usr/lib/postgresql/bin
  file:
    src: "{{ item }}"
    dest: "/usr/lib/postgresql/bin/{{ item | basename }}"
    state: link
  with_fileglob:
    - "/home/postgres/.nix-profile/bin/*"
  become: yes


- name: Create symbolic links from /home/postgres/.nix-profile/share/postgresql to /usr/lib/postgresql/share/postgresql
  file:
    src: "{{ item }}"
    dest: "/usr/lib/postgresql/share/postgresql/{{ item | basename }}"
    state: link
  with_fileglob:
    - "/home/postgres/.nix-profile/share/postgresql/*"
  become: yes

- name: Create symbolic links from /home/postgres/.nix-profile/share/postgresql/extension to /usr/lib/postgresql/share/postgresql/extension
  file:
    src: "{{ item }}"
    dest: "/usr/lib/postgresql/share/postgresql/extension/{{ item | basename }}"
    state: link
  with_fileglob:
    - "/home/postgres/.nix-profile/share/postgresql/extension/*"
  become: yes

- name: create destination directory
  file:
    path: /usr/lib/postgresql/share/postgresql/contrib/
    state: directory
    recurse: yes

# TODO check that these dirs were created correctly in final AMI
- name: Recursively create symbolic links and set permissions for the contrib/postgis-* dir
  shell: >
    sudo mkdir -p /usr/lib/postgresql/share/postgresql/contrib && \
    sudo find /home/postgres/.nix-profile/share/postgresql/contrib/ -mindepth 1 -type d -exec sh -c 'for dir do sudo ln -s "$dir" "/usr/lib/postgresql/share/postgresql/contrib/$(basename "$dir")"; done' sh {} + \
    && chown -R postgres:postgres "/usr/lib/postgresql/share/postgresql/contrib/"
  become: yes

- name: Create symbolic links from /home/postgres/.nix-profile/share/postgresql/timezonesets to /usr/lib/postgresql/share/postgresql/timeszonesets
  file:
    src: "{{ item }}"
    dest: "/usr/lib/postgresql/share/postgresql/timezonesets/{{ item | basename }}"
    state: link
  with_fileglob:
    - "/home/postgres/.nix-profile/share/postgresql/timezonesets/*"
  become: yes

- name: Create symbolic links from /home/postgres/.nix-profile/share/postgresql/tsearch_data to /usr/lib/postgresql/share/postgresql/tsearch_data
  file:
    src: "{{ item }}"
    dest: "/usr/lib/postgresql/share/postgresql/tsearch_data/{{ item | basename }}"
    state: link
  with_fileglob:
    - "/home/postgres/.nix-profile/share/postgresql/tsearch_data/*"
  become: yes


#Install configure before init
- name: Install Postgres extensions
  import_tasks: setup-extensions.yml

- name: Link database data_dir to data volume directory
  file:
    src: "/data/pgdata"
    path: "/var/lib/postgresql/data"
    state: link
    force: yes
    owner: postgres
    group: postgres

- name: Ensure en_US.UTF-8 locale is enabled
  shell: |
    if ! grep -q "^en_US.UTF-8" /etc/locale.gen ; then
        echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        locale-gen
    fi
  become: yes

- name: Initialize the database
  become: yes
  become_user: postgres
  shell: |
    export LOCALE_ARCHIVE=$(nix profile list | grep glibc-locales | tail -n 1 | cut -d ':' -f 2 | sed 's/^[ \t]*//')/lib/locale/locale-archive
    /usr/lib/postgresql/bin/pg_ctl -D /var/lib/postgresql/data initdb -o "--allow-group-access --locale=en_US.UTF-8"
  vars:
    ansible_command_timeout: 60
#     # Circumvents the following error:
#     # "Timeout (12s) waiting for privilege escalation prompt"

- name: copy PG systemd unit
  template:
    src: /tmp/ansible-playbook/files/postgresql_config/postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service

- name: copy optimizations systemd unit
  template:
    src: /tmp/ansible-playbook/files/database-optimizations.service.j2
    dest: /etc/systemd/system/database-optimizations.service

- name: Restart Postgres Database without Systemd
  become: yes
  become_user: postgres
  shell: |
    export LOCALE_ARCHIVE=$(nix profile list | grep glibc-locales | tail -n 1 | cut -d ':' -f 2 | sed 's/^[ \t]*//')/lib/locale/locale-archive
    /usr/lib/postgresql/bin/pg_ctl -D /var/lib/postgresql/data start

- name: Execute init SQL files
  become: yes
  become_user: postgres
  shell:
    cmd: /usr/lib/postgresql/bin/psql -f {{ item }}
  loop: "{{ sql_files }}"

- name: Delete SQL scripts
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ sql_files }}"

- name: Restart Postgres Database without Systemd
  become: yes
  become_user: postgres
  shell: |
    export LOCALE_ARCHIVE=$(nix profile list | grep glibc-locales | tail -n 1 | cut -d ':' -f 2 | sed 's/^[ \t]*//')/lib/locale/locale-archive
    /usr/lib/postgresql/bin/pg_ctl -D /var/lib/postgresql/data restart -o "-c shared_preload_libraries='pg_tle'"


- name: Run migrations
  import_tasks: setup-migrations.yml
  tags:
    - migrations


# # # Reload
- name: System - systemd reload
  systemd:
    enabled: yes
    name: postgresql
    daemon_reload: yes

- name: Stop Postgres with systemd
  systemd:
    state: stopped
    name: postgresql
