- name: Envoy - system user
  user: name=envoy

- name: Kong - download binary
  get_url:
    url: "https://github.com/envoyproxy/envoy/releases/download/v{{ envoy_release }}/envoy-{{ envoy_release }}-linux-aarch_64"
    dest: /tmp/envoy.app
    checksum: "{{ envoy_release_checksum }}"

# [warn] ulimit is currently set to "1024". For better performance set it to at least
# "4096" using "ulimit -n"
- name: Envoy - bump up ulimit
  pam_limits:
    limit_item: nofile
    limit_type: soft
    domain: envoy
    value: "4096"

- name: Envoy - create service file
  template:
    src: files/envoy_config/envoy.service.j2
    dest: /etc/systemd/system/envoy.service

- name: Envoy - disable service
  systemd:
    enabled: no
    name: envoy
    state: stopped
    daemon_reload: yes
