- name: Copy extension packages
  copy:
    src: files/extensions/
    dest: /tmp/extensions/

- name: Install extensions
  apt:
    deb: "/tmp/extensions/{{ item | basename }}"
  with_fileglob: "files/extensions/*.deb"

- name: pg_cron - set cron.database_name
  become: yes
  lineinfile:
    path: /etc/postgresql/postgresql.conf
    state: present
    line: cron.database_name = 'postgres'

- name: pgsodium - determine postgres bin directory
  shell: pg_config --bindir
  register: pg_bindir_output
- set_fact:
    pg_bindir: "{{ pg_bindir_output.stdout }}"

- name: pgsodium - set pgsodium.getkey_script
  become: yes
  lineinfile:
    path: /etc/postgresql/postgresql.conf
    state: present
    # script is expected to be placed by finalization tasks for different target platforms
    line: pgsodium.getkey_script= '{{ pg_bindir }}/pgsodium_getkey.sh'

- name: auto_explain - set auto_explain.log_min_duration
  become: yes
  lineinfile:
    path: /etc/postgresql/postgresql.conf
    state: present
    line: auto_explain.log_min_duration = 10s

- name: Cleanup - extension packages
  file:
    path: /tmp/extensions
    state: absent
