- name: Envoy - system user
  user: name=envoy

- name: Kong - download deb package
  get_url:
    url: "https://github.com/envoyproxy/envoy/releases/download/v{{ envoy_release }}/envoy-{{ envoy_release }}-linux-aarch_64"
    dest: /etc/envoy/envoy
    checksum: "{{ envoy_release_checksum }}"

- name: Kong - configuration
  template:
    src: files/envoy_config/envoy.conf.j2
    dest: /etc/envoy/envoy.conf

- name: Kong - hand over ownership of /usr/local/envoy to user envoy
  file:
    path: /usr/local/envoy
    recurse: yes
    owner: envoy

# [warn] ulimit is currently set to "1024". For better performance set it to at least
# "4096" using "ulimit -n"
- name: Envoy - bump up ulimit
  pam_limits:
    limit_item: nofile
    limit_type: soft
    domain: envoy
    value: "4096"

- name: Envoy - create service file
  template:
    src: files/envoy_config/envoy.service.j2
    dest: /etc/systemd/system/envoy.service

- name: Envoy - disable service
  systemd:
    enabled: no
    name: envoy
    state: stopped
    daemon_reload: yes
