static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/health"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Healthy"
              - match:
                  prefix: "/rest/v1/"
                  headers:
                  - name: apikey
                    string_match:
                      exact: '{{ supabase-api-key-2020-07-28 }}'
                route:
                  cluster: rest
                  prefix_rewrite: "/"
              - match:
                  prefix: "/auth/v1/admin/"
                  headers:
                  - name: apikey
                    string_match:
                      exact: '{{ supabase-api-key-2020-07-28 }}'
                route:
                  cluster: gotrue
                  prefix_rewrite: "/"
              - match:
                  prefix: "/auth/v1/"
                route:
                  cluster: gotrue
                  prefix_rewrite: "/"
              - match:
                  prefix: "/pg/"
                  headers:
                  - name: apikey
                    string_match:
                      exact: '{{ supabase-api-key-2020-07-28 }}'
                route:
                  cluster: pg-v1
                  prefix_rewrite: "/"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: gotrue
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: gotrue
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9998

  - name: rest
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: rest
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3000

  - name: pg-v1
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: pg-v1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1337