- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - git
      - build-essential
      - liblz4-dev
      - libzstd-dev
      - clang-11
      - libcurl4-openssl-dev
      - libkrb5-dev
      - libicu-dev
    state: present

- name: Add PostgreSQL repo and install postgresql-server-dev
  block:
    - name: Add PostgreSQL APT key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: Install postgresql-server-dev-15
      apt:
        name: postgresql-server-dev-15
        state: present

- name: Clone and install Citus
  block:
    - name: Clone Citus repository
      git:
        repo: 'https://github.com/citusdata/citus.git'
        dest: '/tmp/citus'
        clone: yes

    - name: Run ./configure
      command:
        cmd: "./configure"
        chdir: /tmp/citus
      register: configure_result
      ignore_errors: yes

    - name: Check ./configure output
      assert:
        that: configure_result.rc == 0
        fail_msg: "./configure failed with the following output: {{ configure_result.stdout }} {{ configure_result.stderr }}"
        success_msg: "./configure succeeded with the following output: {{ configure_result.stdout }}"
      when: configure_result is defined

    - name: Run make to build Citus
      command:
        cmd: "make"
        chdir: /tmp/citus
      when: configure_result is defined and configure_result.rc == 0

    - name: Install Citus
      command:
        cmd: "make install"
        chdir: /tmp/citus
      when: configure_result is defined and configure_result.rc == 0
