# plrust
- name: plrust - update and install dependencies
  apt:
    name:
      - build-essential
      - ca-certificates
      - clang
      - clang-11
      - gcc
      - git
      - gnupg
      - libssl-dev
      - llvm-11
      - lsb-release
      - make
      - pkg-config
      - wget
    state: present
    update_cache: yes

# required for postgresql-server-dev-XX
- name: plrust - import the PostgreSQL GPG key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: plrust - add PostgreSQL Apt repository
  apt_repository:
    repo: "deb https://apt-archive.postgresql.org/pub/repos/apt focal-pgdg-archive main"
    state: present
    update_cache: yes

- name: plrust - install postgresql-server-dev-XX
  apt:
    name:
      - postgresql-server-dev-{{ postgresql_major }}
    state: present
    update_cache: yes

- name: plrust - install rust
  become: yes
  become_user: postgres
  become_method: su
  shell: |
    wget -qO- https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain={{ plrust_language_version }}
    echo 'source "$HOME/.cargo/env"' >> $HOME/.bashrc
  args:
    creates: "$HOME/.cargo"

- name: plrust - install rust toolchain and set default
  become: yes
  become_user: postgres
  become_method: su
  shell: |
    source $HOME/.cargo/env
    rustup toolchain install {{ plrust_language_version }}
    rustup default {{ plrust_language_version }}
  args:
    executable: /bin/bash

- name: plrust - add rust components and target
  become: yes
  become_user: postgres
  become_method: su
  shell: |
    source $HOME/.cargo/env
    rustup component add llvm-tools-preview rustc-dev
    rustup target install x86_64-unknown-linux-gnu
    rustup target install aarch64-unknown-linux-gnu
  args:
    executable: /bin/bash

- name: plrust - install plrust
  ansible.builtin.apt:
    deb: "https://github.com/tcdi/plrust/releases/download/v{{ plrust_release }}/plrust-trusted-{{ plrust_release }}_{{ plrust_language_version }}-debian-pg{{ postgresql_major }}-{{ platform }}.deb"
