name: Release Ubuntu 18 AMI

on:
  push:
    branches:
      - develop
      - pcnc/build-glibc227-bin
    paths:
      - '.github/workflows/ami-release-ubuntu-18.yml'
      - 'common.vars.pkr.hcl'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, X64]
    timeout-minutes: 150
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build AMI
        run: |
          GIT_SHA=${{github.sha}}
          packer build -var "git-head-version=${GIT_SHA}" -var "packer-execution-id=u18-${GITHUB_RUN_ID}" -var-file="development-arm.vars.pkr.hcl" -var-file="common.vars.pkr.hcl"  -var "skip_create_ami=true" -var "ami=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-*" -var "ami_name=supabase-postgres-u18" amazon-arm64.pkr.hcl

      - name: List files
        id: process_release_version
        run: |
          ls -la /tmp

      - name: Cleanup resources on build cancellation
        if: ${{ cancelled() }}
        run: |
          aws ec2 describe-instances --filters "Name=tag:packerExecutionId,Values=u18-${GITHUB_RUN_ID}" --query "Reservations[].Instances[].InstanceId" --output text | xargs -I {} aws ec2 terminate-instances --instance-ids {}
