name: Package plv8 - multiversion

on:
  push:
    branches:
      - develop
      - pcnc/plv8
    paths:
      - ".github/workflows/package-plv8.yml"
      - "Dockerfile"

env:
  image: ghcr.io/supabase/plv8
permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.image }}:${{ steps.meta.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v3
      - id: meta
        run: |
          plv8_release=$(grep -o 'plv8_release=.*' Dockerfile | head -1 | cut -d "=" -f 2)
          postgresql_major=$(grep -o 'postgresql_major=.*' Dockerfile | head -1 | cut -d "=" -f 2)
          echo "image_tag=${plv8_release}-pg${postgresql_major}" >> $GITHUB_OUTPUT

  build_image:
    needs: settings
    strategy:
      matrix:
        include:
          - postgresql_major: 13
            postgresql_release: 13.3
          - postgresql_major: 14
            postgresql_release: 14.1
          - postgresql_major: 15
            postgresql_release: 15.1
    runs-on: arm-runner
    timeout-minutes: 180
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            postgresql_major=${{ matrix.postgresql_major }}
            postgresql_release=${{ matrix.postgresql_release }}
          push: true
          target: plv8-deb
          tags: 3.2.2-pg${{ matrix.postgresql_major }}_arm64
          platforms: linux/arm64
          no-cache: true
